INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_BLACKWOOD_ADAPTIVETIME Blackwood_AdaptiveTime)

FIND_PATH(
    BLACKWOOD_ADAPTIVETIME_INCLUDE_DIRS
    NAMES Blackwood_AdaptiveTime/api.h
    HINTS $ENV{BLACKWOOD_ADAPTIVETIME_DIR}/include
        ${PC_BLACKWOOD_ADAPTIVETIME_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    BLACKWOOD_ADAPTIVETIME_LIBRARIES
    NAMES gnuradio-Blackwood_AdaptiveTime
    HINTS $ENV{BLACKWOOD_ADAPTIVETIME_DIR}/lib
        ${PC_BLACKWOOD_ADAPTIVETIME_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(BLACKWOOD_ADAPTIVETIME DEFAULT_MSG BLACKWOOD_ADAPTIVETIME_LIBRARIES BLACKWOOD_ADAPTIVETIME_INCLUDE_DIRS)
MARK_AS_ADVANCED(BLACKWOOD_ADAPTIVETIME_LIBRARIES BLACKWOOD_ADAPTIVETIME_INCLUDE_DIRS)

