INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_BLACKWOOD_MODULETWO Blackwood_moduletwo)

FIND_PATH(
    BLACKWOOD_MODULETWO_INCLUDE_DIRS
    NAMES Blackwood_moduletwo/api.h
    HINTS $ENV{BLACKWOOD_MODULETWO_DIR}/include
        ${PC_BLACKWOOD_MODULETWO_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    BLACKWOOD_MODULETWO_LIBRARIES
    NAMES gnuradio-Blackwood_moduletwo
    HINTS $ENV{BLACKWOOD_MODULETWO_DIR}/lib
        ${PC_BLACKWOOD_MODULETWO_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(BLACKWOOD_MODULETWO DEFAULT_MSG BLACKWOOD_MODULETWO_LIBRARIES BLACKWOOD_MODULETWO_INCLUDE_DIRS)
MARK_AS_ADVANCED(BLACKWOOD_MODULETWO_LIBRARIES BLACKWOOD_MODULETWO_INCLUDE_DIRS)

